//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.27 at 12:21:13 AM CDT 
//


package com.blizzard.api.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.blizzard.api.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.blizzard.api.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Testsuite.Testset }
     * 
     */
    public Testsuite.Testset createTestsuiteTestset() {
        return new Testsuite.Testset();
    }

    /**
     * Create an instance of {@link Testsuite.Testset.Testcase.Param }
     * 
     */
    public Testsuite.Testset.Testcase.Param createTestsuiteTestsetTestcaseParam() {
        return new Testsuite.Testset.Testcase.Param();
    }

    /**
     * Create an instance of {@link Testsuite.Testset.Testcase }
     * 
     */
    public Testsuite.Testset.Testcase createTestsuiteTestsetTestcase() {
        return new Testsuite.Testset.Testcase();
    }

    /**
     * Create an instance of {@link Testsuite }
     * 
     */
    public Testsuite createTestsuite() {
        return new Testsuite();
    }

}
