//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.27 at 12:21:13 AM CDT 
//


package com.blizzard.api.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="testset" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="testcase" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="param" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="endpointurl" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="urlextn" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="httpmethod" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="queryString" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="runmode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="baseurl" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="runmode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="publicKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sigkey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "testset"
})
@XmlRootElement(name = "testsuite")
public class Testsuite {

    protected List<Testsuite.Testset> testset;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    @XmlSchemaType(name = "anyURI")
    protected String baseurl;
    @XmlAttribute
    protected String runmode;
    @XmlAttribute
    protected String publicKey;
    @XmlAttribute
    protected String sigkey;

    /**
     * Gets the value of the testset property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the testset property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTestset().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Testsuite.Testset }
     * 
     * 
     */
    public List<Testsuite.Testset> getTestset() {
        if (testset == null) {
            testset = new ArrayList<Testsuite.Testset>();
        }
        return this.testset;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the baseurl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseurl() {
        return baseurl;
    }

    /**
     * Sets the value of the baseurl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseurl(String value) {
        this.baseurl = value;
    }

    /**
     * Gets the value of the runmode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRunmode() {
        return runmode;
    }

    /**
     * Sets the value of the runmode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRunmode(String value) {
        this.runmode = value;
    }

    /**
     * Gets the value of the publicKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicKey() {
        return publicKey;
    }

    /**
     * Sets the value of the publicKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicKey(String value) {
        this.publicKey = value;
    }

    /**
     * Gets the value of the sigkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSigkey() {
        return sigkey;
    }

    /**
     * Sets the value of the sigkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSigkey(String value) {
        this.sigkey = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="testcase" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="param" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="endpointurl" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="urlextn" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="httpmethod" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="queryString" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="runmode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "testcase"
    })
    public static class Testset {

        protected List<Testsuite.Testset.Testcase> testcase;
        @XmlAttribute
        protected String name;
        @XmlAttribute
        protected String runmode;

        /**
         * Gets the value of the testcase property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the testcase property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTestcase().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Testsuite.Testset.Testcase }
         * 
         * 
         */
        public List<Testsuite.Testset.Testcase> getTestcase() {
            if (testcase == null) {
                testcase = new ArrayList<Testsuite.Testset.Testcase>();
            }
            return this.testcase;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the runmode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRunmode() {
            return runmode;
        }

        /**
         * Sets the value of the runmode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRunmode(String value) {
            this.runmode = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="param" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="endpointurl" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="urlextn" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="httpmethod" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="queryString" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "param"
        })
        public static class Testcase {

            protected List<Testsuite.Testset.Testcase.Param> param;
            @XmlAttribute
            protected Byte id;
            @XmlAttribute
            protected String name;
            @XmlAttribute
            protected String desc;
            @XmlAttribute
            protected String endpointurl;
            @XmlAttribute
            protected String urlextn;
            @XmlAttribute
            protected String httpmethod;
            @XmlAttribute
            protected String queryString;

            /**
             * Gets the value of the param property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the param property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getParam().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Testsuite.Testset.Testcase.Param }
             * 
             * 
             */
            public List<Testsuite.Testset.Testcase.Param> getParam() {
                if (param == null) {
                    param = new ArrayList<Testsuite.Testset.Testcase.Param>();
                }
                return this.param;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setId(Byte value) {
                this.id = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the desc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDesc() {
                return desc;
            }

            /**
             * Sets the value of the desc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDesc(String value) {
                this.desc = value;
            }

            /**
             * Gets the value of the endpointurl property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEndpointurl() {
                return endpointurl;
            }

            /**
             * Sets the value of the endpointurl property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEndpointurl(String value) {
                this.endpointurl = value;
            }

            /**
             * Gets the value of the urlextn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUrlextn() {
                return urlextn;
            }

            /**
             * Sets the value of the urlextn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUrlextn(String value) {
                this.urlextn = value;
            }

            /**
             * Gets the value of the httpmethod property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHttpmethod() {
                return httpmethod;
            }

            /**
             * Sets the value of the httpmethod property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHttpmethod(String value) {
                this.httpmethod = value;
            }

            /**
             * Gets the value of the queryString property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getQueryString() {
                return queryString;
            }

            /**
             * Sets the value of the queryString property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setQueryString(String value) {
                this.queryString = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Param {

                @XmlValue
                protected String value;
                @XmlAttribute
                protected String id;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the id property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setId(String value) {
                    this.id = value;
                }

            }

        }

    }

}
